Macos build fixes
i2p/libsam3 pull request #23
Opened 2024-02-07 16:48 UTC by eyedeekay

Fix for issue #20 on OSX, I don't use either Retroshare or Mac OSX as a daily driver so I'll need some help testing it

2024-02-08 05:58 UTC, barracuda156 commented
Does not work as yet. This is on Sonoma:

```
--->  Applying patches to libsam3
--->  Applying 0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3/libsam3.h'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Configuring libsam3
--->  Building libsam3
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/make -j4 -w build CC="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang" CXX="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cxx/usr/bin/clang++" OBJC="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objc/usr/bin/clang" OBJCXX="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr/bin/clang++" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e'
/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -c src/libsam3/libsam3.c -o src/libsam3/libsam3.o
/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -c src/libsam3a/libsam3a.c -o src/libsam3a/libsam3a.o
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: clang: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]

In file included from src/libsam3a/libsam3a.c:26:
src/libsam3a/libsam3a.h:69:46: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
extern uint64_t sam3atimeval2ms(const struct timeval *tv);
                                             ^
src/libsam3a/libsam3a.h:70:36: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
extern void sam3ams2timeval(struct timeval *tv, uint64_t ms);
                                   ^
src/libsam3/libsam3.c:56:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
src/libsam3a/libsam3a.c:66:18: error: call to undeclared function 'mach_absolute_time'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  uint64_t mat = mach_absolute_time();
                 ^
src/libsam3a/libsam3a.c:79:10: error: conflicting types for 'sam3atimeval2ms'
uint64_t sam3atimeval2ms(const struct timeval *tv) {
         ^
src/libsam3a/libsam3a.h:69:17: note: previous declaration is here
extern uint64_t sam3atimeval2ms(const struct timeval *tv);
                ^
src/libsam3a/libsam3a.c:83:6: error: conflicting types for 'sam3ams2timeval'
void sam3ams2timeval(struct timeval *tv, uint64_t ms) {
     ^
src/libsam3a/libsam3a.h:70:13: note: previous declaration is here
extern void sam3ams2timeval(struct timeval *tv, uint64_t ms);
            ^
src/libsam3a/libsam3a.c:143:7: error: call to undeclared function 'ioctl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if (ioctl(fd, FIONREAD, &av) < 0)
      ^
src/libsam3a/libsam3a.c:143:17: error: use of undeclared identifier 'FIONREAD'
  if (ioctl(fd, FIONREAD, &av) < 0)
                ^
src/libsam3a/libsam3a.c:153:15: error: call to undeclared function 'gethostbyname'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if ((host = gethostbyname(hostname)) == NULL || host->h_name == NULL ||
              ^
src/libsam3a/libsam3a.c:153:15: note: did you mean 'gethostname'?
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/unistd.h:626:6: note: 'gethostname' declared here
int      gethostname(char *, size_t);
         ^
src/libsam3a/libsam3a.c:153:13: warning: incompatible integer to pointer conversion assigning to 'struct hostent *' from 'int' [-Wint-conversion]
  if ((host = gethostbyname(hostname)) == NULL || host->h_name == NULL ||
            ^ ~~~~~~~~~~~~~~~~~~~~~~~
src/libsam3a/libsam3a.c:153:55: error: incomplete definition of type 'struct hostent'
  if ((host = gethostbyname(hostname)) == NULL || host->h_name == NULL ||
                                                  ~~~~^
src/libsam3a/libsam3a.c:149:10: note: forward declaration of 'struct hostent'
  struct hostent *host;
         ^
src/libsam3a/libsam3a.c:154:12: error: incomplete definition of type 'struct hostent'
      !host->h_addr_list[0][0]) {
       ~~~~^
src/libsam3a/libsam3a.c:149:10: note: forward declaration of 'struct hostent'
  struct hostent *host;
         ^
src/libsam3a/libsam3a.c:159:33: error: incomplete definition of type 'struct hostent'
  return ((struct in_addr *)host->h_addr_list[0])->s_addr;
                            ~~~~^
src/libsam3a/libsam3a.c:149:10: note: forward declaration of 'struct hostent'
  struct hostent *host;
         ^
src/libsam3a/libsam3a.c:159:50: error: incomplete definition of type 'struct in_addr'
  return ((struct in_addr *)host->h_addr_list[0])->s_addr;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
src/libsam3a/libsam3a.c:159:19: note: forward declaration of 'struct in_addr'
  return ((struct in_addr *)host->h_addr_list[0])->s_addr;
                  ^
src/libsam3a/libsam3a.c:171:13: error: call to undeclared function 'socket'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if ((fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0)) < 0)
            ^
src/libsam3a/libsam3a.c:171:20: error: use of undeclared identifier 'AF_INET'
  if ((fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0)) < 0)
                   ^
1 error generated.
src/libsam3a/libsam3a.c:171:29: error: use of undeclared identifier 'SOCK_STREAM' [...]

2024-02-08 06:18 UTC, barracuda156 requested changes
These are not sufficient, but appear necessary.

2024-02-08 06:18 UTC, barracuda156 commented on src/libsam3a/libsam3a.c
> +#if defined(__unix__) || !defined(__APPLE__)
_Perhaps_ should be AND, not OR?

2024-02-08 06:18 UTC, barracuda156 commented on src/libsam3/libsam3.c
>  #include <sys/sysinfo.h>
```suggestion
```

2024-02-08 06:18 UTC, barracuda156 commented on src/libsam3a/libsam3a.c
> +#if defined(__unix__) || !defined(__APPLE__)
```suggestion
#if defined(__unix__) && !defined(__APPLE__)
```

2024-02-08 06:18 UTC, barracuda156 commented on src/libsam3/libsam3.c
>  #endif
```suggestion
#endif

#if defined(__unix__) && !defined(__APPLE__)
#include <sys/sysinfo.h>
#endif

```

2024-02-08 06:18 UTC, barracuda156 commented on src/libsam3a/libsam3a.c
> +#if defined(__APPLE__)
```suggestion
#if defined(__APPLE__)
#include <mach/mach_time.h>

```

2024-02-09 14:02 UTC, barracuda156 commented on src/libsam3/libsam3.c
>  #include <sys/sysinfo.h>
It is included below but not removed from here.

2024-02-11 04:32 UTC, barracuda156 commented
@eyedeekay I am getting errors with `libsam3a.c` now:
```
--->  Applying patches to libsam3
--->  Applying 0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3/libsam3.h'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0004-Update-src-libsam3-libsam3.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0004-Update-src-libsam3-libsam3.c.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0005-Update-src-libsam3a-libsam3a.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0005-Update-src-libsam3a-libsam3a.c.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0006-Use-getpid-and-TickCount-when-on-OSX-platforms.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0006-Use-getpid-and-TickCount-when-on-OSX-platforms.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0007-Include-mach_time-on-osx-platforms.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0007-Include-mach_time-on-osx-platforms.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0008-Remove-sysinfo.h-from-the-Apple-header-section.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0008-Remove-sysinfo.h-from-the-Apple-header-section.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0009-Update-src-libsam3a-libsam3a.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0009-Update-src-libsam3a-libsam3a.c.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0010-extern-sam3atimeval2ms-sam3ams2timeval.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0010-extern-sam3atimeval2ms-sam3ams2timeval.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Configuring libsam3
--->  Building libsam3
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/make -j4 -w build CC="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang" CXX="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cxx/usr/bin/clang++" OBJC="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objc/usr/bin/clang" OBJCXX="/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr/bin/clang++" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e'
/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -c src/libsam3/libsam3.c -o src/libsam3/libsam3.o
/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/clang -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -arch arm64 -c src/libsam3a/libsam3a.c -o src/libsam3a/libsam3a.o
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/opt/local/lib' [-Wunused-command-line-argument]
In file included from src/libsam3a/libsam3a.c:26:
src/libsam3a/libsam3a.h:69:46: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
extern uint64_t sam3atimeval2ms(const struct timeval *tv);
                                             ^
src/libsam3a/libsam3a.h:70:36: warning: declaration of 'struct timeval' will not be visible outside of this function [-Wvisibility]
extern void sam3ams2timeval(struct timeval *tv, uint64_t ms);
                                   ^
src/libsam3a/libsam3a.c:82:17: error: conflicting types for 'sam3atimeval2ms'
extern uint64_t sam3atimeval2ms(const struct timeval *tv) {
                ^
src/libsam3a/libsam3a.h:69:17: note: previous declaration is here
extern uint64_t sam3atimeval2ms(const struct timeval *tv);
                ^
src/libsam3a/libsam3a.c:86:13: error: conflicting types for 'sam3ams2timeval'
extern void sam3ams2timeval(struct timeval *tv, uint64_t ms) {
            ^
src/libsam3a/libsam3a.h:70:13: note: previous declaration is here
extern void sam3ams2timeval(struct timeval *tv, uint64_t ms);
            ^
src/libsam3a/libsam3a.c:146:7: error: call to undeclared function 'ioctl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if (ioctl(fd, FIONREAD, &av) < 0)
      ^
src/libsam3a/libsam3a.c:146:17: error: use of undeclared identifier 'FIONREAD'
  if (ioctl(fd, FIONREAD, &av) < 0)
                ^
src/libsam3a/libsam3a.c:156:15: error: call to undeclared function 'gethostbyname'; ISO C99 and later do not support implicit function declarations [-W [...]

2024-02-12 14:14 UTC, eyedeekay commented
Working on these today, honestly looks like I'm going to spend the day on stack overflow cross-referencing these errors.

2024-02-13 15:43 UTC, eyedeekay commented
Down to the last 4, soon to be the last 2

2024-02-13 17:11 UTC, eyedeekay commented
OK I think that's got it, please confirm when you can @barracuda156

2024-02-14 16:15 UTC, barracuda156 commented
@eyedeekay Thank you, let me try.

2024-02-14 16:21 UTC, barracuda156 commented
@eyedeekay Awesome, it builds now, at least on Sonoma. I will try now on a couple of older systems and with GCC instead of Clang.

```
--->  Extracting libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/libsam3/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e.tar.gz' | /usr/bin/tar -xf - 
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objc
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objc/usr
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objc/usr/bin
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cxx
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cxx/usr
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/cxx/usr/bin
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objcxx
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr
xinstall: mkdir /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr/bin
--->  Applying patches to libsam3
--->  Applying 0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0001-Fix-some-of-the-headers-to-make-progress-on-fixing-O.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3/libsam3.h'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0002-Use-PID-TickCount-for-random-nickname-string-on-__AP.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0003-Disable-use-of-sysinfo.h-on-Mac-OSX-and-replace-depr.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0004-Update-src-libsam3-libsam3.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0004-Update-src-libsam3-libsam3.c.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0005-Update-src-libsam3a-libsam3a.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0005-Update-src-libsam3a-libsam3a.c.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0006-Use-getpid-and-TickCount-when-on-OSX-platforms.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0006-Use-getpid-and-TickCount-when-on-OSX-platforms.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0007-Include-mach_time-on-osx-platforms.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0007-Include-mach_time-on-osx-platforms.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0008-Remove-sysinfo.h-from-the-Apple-header-section.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0008-Remove-sysinfo.h-from-the-Apple-header-section.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0009-Update-src-libsam3a-libsam3a.c.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0009-Update-src-libsam3a-libsam3a.c.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0010-extern-sam3atimeval2ms-sam3ams2timeval.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0010-extern-sam3atimeval2ms-sam3ams2timeval.patch'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0011-since-SOL_SOCKET-doesn-t-exist-on-Mac-pass-SOL_TCP-o.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0011-since-SOL_SOCKET-doesn-t-exist-on-Mac-pass-SOL_TCP-o.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0012-that-was-a-misidentification-use-netinet-tcp-instead.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0012-that-was-a-misidentification-use-netinet-tcp-instead.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0013-that-was-a-misidentification-use-netinet-tcp-instead.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0013-that-was-a-misidentification-use-netinet-tcp-instead.patch'
patching file 'src/libsam3/libsam3.c'
--->  Applying 0014-It-needs-to-go-in-sam3a.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPorts/security/libsam3/files/0014-It-needs-to-go-in-sam3a.patch'
patching file 'src/libsam3/libsam3.c'
patching file 'src/libsam3a/libsam3a.c'
--->  Applying 0015-Include-section-needs-to-be-true-if-__APPLE__-is-def.patch
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/patch -p0 < '/opt/svacchanda/SonomaPo [...]

2024-02-14 16:46 UTC, barracuda156 commented
@eyedeekay UPD. On an older macOS `MSG_NOSIGNAL` is undefined:
```
--->  Building libsam3
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/make -j6 -w build CC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/gcc-4.2" CXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cxx/usr/bin/g++-4.2" OBJC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/objc/usr/bin/gcc-4.2" OBJCXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr/bin/g++-4.2" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e'
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/gcc-4.2 -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -c src/libsam3/libsam3.c -o src/libsam3/libsam3.o
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/gcc-4.2 -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -c src/libsam3a/libsam3a.c -o src/libsam3a/libsam3a.o
src/libsam3/libsam3.c: In function ‘sam3tcpSend’:
src/libsam3/libsam3.c:215: error: ‘MSG_NOSIGNAL’ undeclared (first use in this function)
src/libsam3/libsam3.c:215: error: (Each undeclared identifier is reported only once
src/libsam3/libsam3.c:215: error: for each function it appears in.)
src/libsam3a/libsam3a.c: In function ‘sam3aSendBytes’:
src/libsam3a/libsam3a.c:231: error: ‘MSG_NOSIGNAL’ undeclared (first use in this function)
src/libsam3a/libsam3a.c:231: error: (Each undeclared identifier is reported only once
src/libsam3a/libsam3a.c:231: error: for each function it appears in.)
make: *** [src/libsam3/libsam3.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/libsam3a/libsam3a.o] Error 1
```
Could we address this in some reasonable way?

2024-02-16 05:55 UTC, barracuda156 commented
@eyedeekay Apparently `MSG_NOSIGNAL` is missing on macOS as late as 10.15 (Catalina), which is rather recent, but there is way to fix it:
https://github.com/kovidgoyal/kitty/commit/aa0b07a90d8158fb7231462f62c745f408231f0a
See also: https://github.com/lpeterse/haskell-socket/issues/8

2024-02-18 00:08 UTC, eyedeekay commented
Fixed it this morning but had connectivity issues that prevented me from pinging you here. I finally got my Mac unbricked, but updating it seems to be part of what causes it to break so I'm stuck back on High Sierra. Hopefully this is the last one.

2024-02-18 02:32 UTC, barracuda156 commented
@eyedeekay One last thing, sorry: we also need the same block in `libsam3.c`, something like:

```
--- libsam3.c
+++ libsam3.c
@@ -63,6 +63,9 @@
 
 #if defined(__APPLE__)
 #include <mach/mach_time.h>
+#ifndef MSG_NOSIGNAL
+#define MSG_NOSIGNAL 0
+#endif
 uint32_t TickCount() {
   uint64_t mat = mach_absolute_time();
   uint32_t mul = 0x80d9594e;
```

With that it builds fine:
```
--->  Building libsam3
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e" && /usr/bin/make -j6 -w build CC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/gcc-4.2" CXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cxx/usr/bin/g++-4.2" OBJC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/objc/usr/bin/gcc-4.2" OBJCXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/objcxx/usr/bin/g++-4.2" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e'
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/compwrap/cc/usr/bin/gcc-4.2 -Wall -g -O2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -c src/libsam3/libsam3.c -o src/libsam3/libsam3.o
powerpc-apple-darwin10-gcc-4.2.1: -headerpad_max_install_names: linker input file unused because linking not done
ar -sr libsam3.a src/libsam3/libsam3.o src/libsam3a/libsam3a.o
ar: creating archive libsam3.a
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_libsam3/libsam3/work/libsam3-2226ef0a20a001ec0942be6abe5e909c15447d8e'
```

2024-02-18 18:10 UTC, eyedeekay commented
Awesome thanks for testing, added that block, once you confirm it works I'll merge this.

2024-02-25 09:11 UTC, barracuda156 commented
@eyedeekay Could we merge this then?

2024-02-25 20:01 UTC, merged

2024-02-26 03:45 UTC, barracuda156 commented
@eyedeekay Thank you!